apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-ms-deployment
  namespace: user-service-ms-namespace
spec:
  selector:
    matchLabels:
      app: order-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-app-container
          image: abhishekvanaras/order-service-ms:2.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9197
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.default.svc.cluster.local:3306/ms-service?allowPublicKeyRetrieval=true&useSSL=false
            - name: DB_NAME
              value: ms-service
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: test1234
