apiVersion: v1
kind: Service
metadata:
  name: order-service-ms-service
  namespace: order-service-ms-namespace
spec:
  selector:
    app: order-deployment
  ports:
    - protocol: "TCP"
      port: 9197
      targetPort: 9197
  type: NodePort